// This file is auto-generated by src/integrations/icons/utils/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/integrations/icons/utils/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { LuArrowRight, LuBookOpen, LuChevronRight, LuClock, LuContact, LuGlobe, LuImage, LuMail, LuMapPin, LuPhone, LuSettings } from 'react-icons/lu';
import { FaArrowsUpDownLeftRight, FaBullseye, FaChevronLeft, FaChevronRight, FaClockRotateLeft, FaCompass, FaEye, FaFeather, FaFileLines, FaHeadset, FaLayerGroup, FaLifeRing, FaLink, FaPalette, FaQuoteLeft, FaRobot, FaRotateLeft, FaScaleBalanced, FaShieldHalved, FaStar, FaUniversalAccess, FaWandMagicSparkles, FaXmark } from 'react-icons/fa6';
import { SiFacebook, SiInstagram } from 'react-icons/si';

export const iconMap = {
  'fa6:arrows-up-down-left-right': FaArrowsUpDownLeftRight,
  'fa6:bullseye': FaBullseye,
  'fa6:chevron-left': FaChevronLeft,
  'fa6:chevron-right': FaChevronRight,
  'fa6:clock-rotate-left': FaClockRotateLeft,
  'fa6:compass': FaCompass,
  'fa6:eye': FaEye,
  'fa6:feather': FaFeather,
  'fa6:file-lines': FaFileLines,
  'fa6:headset': FaHeadset,
  'fa6:layer-group': FaLayerGroup,
  'fa6:life-ring': FaLifeRing,
  'fa6:link': FaLink,
  'fa6:palette': FaPalette,
  'fa6:quote-left': FaQuoteLeft,
  'fa6:robot': FaRobot,
  'fa6:rotate-left': FaRotateLeft,
  'fa6:scale-balanced': FaScaleBalanced,
  'fa6:shield-halved': FaShieldHalved,
  'fa6:star': FaStar,
  'fa6:universal-access': FaUniversalAccess,
  'fa6:wand-magic-sparkles': FaWandMagicSparkles,
  'fa6:xmark': FaXmark,
  'lu:arrow-right': LuArrowRight,
  'lu:book-open': LuBookOpen,
  'lu:chevron-right': LuChevronRight,
  'lu:clock': LuClock,
  'lu:contact': LuContact,
  'lu:globe': LuGlobe,
  'lu:image': LuImage,
  'lu:mail': LuMail,
  'lu:map-pin': LuMapPin,
  'lu:phone': LuPhone,
  'lu:settings': LuSettings,
  'si:facebook': SiFacebook,
  'si:instagram': SiInstagram,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
